---
vaultwarden_version: 1.34.1

# Directory where your data will be stored on the host.
vaultwarden_data_dir: "{{ ansible_storage_dir }}/vaultwarden-data"

## Admin token.
## This token allows access to the admin interface.
## If not set, a random token will be generated on first run and written to a file.
vaultwarden_admin_token: "{{ secret_vaultwarden_admin_token | default(omit) }}"

## Database options.
vaultwarden_pgsql_database: "{{ secret_vaultwarden_pgsql_database | default('vaultwarden') }}"
vaultwarden_pgsql_user: "{{ secret_vaultwarden_pgsql_user | default('vaultwarden') }}"
vaultwarden_pgsql_password: "{{ secret_vaultwarden_pgsql_password | default('vaultwarden') }}"

vaultwarden_pgsql_options:
  max_connections: 100
  shared_buffers: 128MB
  maintenance_work_memory: 64MB
  effective_io_concurrency: 1
  work_memory: 4MB
  max_worker_processes: 8
  max_parallel_workers_per_gather: 2
  max_parallel_workers: 8
  max_parallel_maintenance_workers: 2
  checkpoint_completion_target: 0.5
  wal_buffers: -1 # -1 means Postgres auto-calculates
  min_wal_size: 80MB
  max_wal_size: 1GB
  effective_cache_size: 4GB
  default_statistics_target: 100
  random_page_cost: 4.0

## Extra configuration.
## Additional environment variables to add to the .env file.
vaultwarden_extra_config: ""
# Example:
#   vaultwarden_extra_config: |
#     SIGNUPS_ALLOWED=true
#     IP_HEADER=X-Real-IP
