---
- name: Ensure all Vault directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ ansible_docker_dir }}"
    - "{{ vault_unseal_keys_output_dir }}"
    - "{{ vault_root_token_output_dir }}"

- name: Clone 'docker-compose-vault' into place
  ansible.builtin.git:
    repo: "{{ vault_git_repo }}"
    dest: "{{ vault_compose_root }}"
    version: main
    update: false
    accept_hostkey: true
  register: vault_repo
  changed_when: vault_repo.after != vault_repo.before

- name: Ensure Vault compose stack is started
  community.docker.docker_compose_v2:
    project_src: "{{ vault_compose_root }}"
    state: present

- name: Check Vault status
  community.docker.docker_compose_v2_exec:
    service: vault
    command: vault status -format=json
    project_src: "{{ vault_compose_root }}"
  register: vault_status
  changed_when: false
  failed_when: false

- ansible.builtin.set_fact:
    vault_initialized: "{{ vault_status.stdout is defined and (vault_status.stdout | from_json).initialized | bool | default(false) }}"

- name: Initialize Vault
  when: not vault_initialized
  block:
    - name: Initialize Vault
      community.docker.docker_compose_v2_exec:
        service: vault
        command: "{{ vault_init_command }}"
        project_src: "{{ vault_compose_root }}"
      register: vault_init_output
      changed_when: true

    - name: Parse output of vault init
      ansible.builtin.set_fact:
        vault_root_token: "{{ (vault_init_output.stdout | from_json).root_token }}"
        vault_unseal_keys: "{{ (vault_init_output.stdout | from_json).unseal_keys_hex | flatten(levels=1) }}"
      no_log: true

    - name: Write unseal keys to file
      ansible.builtin.copy:
        dest: "{{ vault_compose_root }}/keys/vault_unseal_key_{{ index }}"
        content: "{{ item }}"
        mode: "0644"
      loop: "{{ vault_unseal_keys }}"
      loop_control:
        index_var: index
      when: vault_init_write_keys

    - name: Write root token to file
      ansible.builtin.copy:
        dest: "{{ vault_compose_root }}/keys/vault_root_token"
        content: "{{ vault_root_token }}"
        mode: "0644"
      when: vault_init_write_keys
